#!/usr/bin/env node
'use strict';
// No dependencies. Rebuild after editing chatbot-topics.txt; --check is used in CI.
const fs = require('node:fs');
const path = require('node:path');
const root = path.join(__dirname, '..');
const source = fs.readFileSync(path.join(__dirname, 'chatbot-topics.txt'), 'utf8');
const topics = source.split('\n').filter(line => !line.startsWith('#')).join('\n').trim().split(/\n\s*\n/).map(block => {
  const lines = block.split('\n');
  if (lines.length !== 4) throw new Error(`Expected four lines per topic: ${lines[0]}`);
  const [id, label] = lines[0].split('|').map(s => s.trim());
  const list = line => line.split(';').map(s => s.trim()).filter(Boolean);
  return { id, label, keys: list(lines[1]), reply: lines[2], questions: list(lines[3]) };
});
const content = `/* Generated by node scripts/build-chatbot.js. Edit scripts/chatbot-topics.txt instead. */\n(function (root) {\n  'use strict';\n  const topics = ${JSON.stringify(topics, null, 2)};\n  if (typeof module === 'object' && module.exports) module.exports = topics;\n  else root.CHATBOT_TOPICS = topics;\n})(typeof globalThis !== 'undefined' ? globalThis : this);\n`;
const output = path.join(root, 'assets/chatbot-data.js');
if (process.argv.includes('--check')) {
  if (!fs.existsSync(output) || fs.readFileSync(output, 'utf8') !== content) {
    throw new Error('Chatbot data is stale. Run node scripts/build-chatbot.js.');
  }
} else fs.writeFileSync(output, content);
console.log(`${topics.length} topics, ${topics.reduce((sum, topic) => sum + topic.questions.length, 0)} authored scripted inputs.`);
